config/routes.rb
RottenMangoes::Application.routes.draw do
  
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'movies#index'

  
  namespace :admin do
    resources :users, only: [:index] do 
      member do
        post :impersonate
      end
    end
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews

  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :only_admins
  
  def index
    @users = User.order(created_at: :desc)
  end

  def impersonate
    @user = User.find params[:id]
    session[:actual_user_id] = session[:user_id]
    session[:user_id] = @user.id
    redirect_to admin_users_path
  end

  private 

  def only_admins
    redirect_to(root_path) unless admin?
  end

  def admin?
    current_user && (current_user.admin? || impersonating?)
  end

  def impersonating?
    if session[:actual_user_id].present?
      user = User.find(session[:actual_user_id])
      user.admin?
    else
      false
    end
  end

  helper_method :admin?, :impersonating?
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_user.html.erb
<tr>
  <td>
    <%= user.firstname %>
  </td>
  <td>
    <%= user.lastname %>
  </td>
  <td>
    <%= link_to 'Impersonate', impersonate_admin_user_path(user), method: :post, confirm: 'Sure dude?' %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<h1>All Users</h1>

<table>
  
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <%# @users.each do |user| %>
    <%#= render 'user', user: user %>
  <%# end %>

  <%#= render partial: 'user', collection: @users %>
  
  <%= render @users %>

</table>